### PR TITLE
Update dependencies to latest versions

### PR DESCRIPTION
**Pull request by hansenmc**
Update dependencies to the latest versions and consolidate dependencies and plugins definitions

53 of the dependencies were outdated, and had at least 3 known vulnerabilities.
https://www.versioneye.com/user/projects/57a52a376725bd0436ad61d0?child=summary
- Updated dependencies to use the latest versions
  - commons-lang changed to org.apache and artifactId renamed to commons-lang3
  - org.htrace changed to org.apache.htrace
  - commons-httpclient changed to org.apache.httpcomponents
  - org.codehaus.jackson changed to com.fasterxml.jackson
  - xpp3 changed to org.ogce
- Consolidated common dependencies and plugins in the parent pom, making sure that common versions are used in the child modules
- Leverage project properties for repeated dependency versions (makes upgrading easier and ensures that consistent version is applied for a given family of jars)
- Resolved conflicts, excluding some transitive dependencies and adding explicit dependency to eliminate conflicts and ensure the latest versions are used.
- sorted dependencies and plugins by groupId, then artifactId
- Adjusted RDFReader and CompressedRDFReader to adjust for API changes from upgrading JENA and TestImportBigData for changes from upgrading Guava.
- Removed local copies of saxon9he and bliki-core jar files from /src/lib/, replaced with standard Maven Central dependency resolution (with the latest versions).
- Added Jacoco plugin, in order to generate code coverage reports for unit tests

### CODE REVIEW

**Comment by jxchen-us** [comment]
Hi Mads, 

Thank you for the patch!

A big part of the mlcp dependencies come from the specific version of Hadoop mlcp is required to support.  In MarkLogic 9, the lowest version of Apache Hadoop that we need to align to is 2.6.

Can you include a list of tests that pass with this patch?

Thanks,
Jane

**Comment by hansenmc** [comment]
I can adjust the dependencies to align with 2.6 (latest is 2.6.4) if we need to, just to be sure that we are compatible with Hadoop 2.6. It looks like the major change from 2.6.x to 2.7.x is that support for Java 6 was dropped, but MLCP compiles to 1.7 already.

I can post the results of the tests, but I did have several tests fail on /develop even before I started making dependency changes. Is that expected? There were at least a few instances in which methods were being invoked that threw exceptions because they did not exist, such as `xdmp:document-get-metadata()`. I am running MarkLogic v9-ea2. I saw that at least one method was migrated from `admin:` to `xdmp:` that was failing when run against MarkLogic v8 and succeeded against v9. I'm curious if these tests are leveraging MarkLogic new functions that are not in the current EA builds?

Also, it seems that tests are disabled by default in the mapreduce module with the property `<skipTests>true</skipTests>`. We should probably flip that to be enabled by default, otherwise tests are not executed with standard builds.

**Comment by jxchen-us** [comment]
That's a good catch.  mlcp on Develop is required to work against any version of MarkLogic 8 Server.  We'll file bugs and fix them.

Apache Hadoop 2.6.4 seems a good start.  We test against CDH 5.4 and HDP 2.4 at the moment in house.
________________________________

**Comment by mattsunsjf** [comment]
Issue #10 has been created for admin: to xdmp: change.

**Comment by hansenmc** [comment]
I have changed the Hadoop dependencies for both to Hadoop v2.6.4 (and adjusted to resolve dependency conflicts). 

We should consider keeping the mapreduce module set for 2.6.4, but bumping up the MLCP Hadoop dependencies to the latest v2.7.x, since the MLCP code works either way and MLCP runs as a standalone commandline tool. That way MLCP could take advantage of the latest-and-greatest security and bug fixes in Hadoop 2.7.x modules. 

I can easily do that in this PR branch. Let me know if you would like me to make that adjustment.

**Comment by jxchen-us** [comment]
Mlcp has the same Hadoop version/distro support requirements as Hadoop Connector.

**Comment by mattsunsjf** [comment]
Hi Mads,
1. With your "Consolidated common dependencies and plugins in the parent pom", are we able to build mapreduce/mlcp separately from their own directory?
2. With commit cb6f1a95b8f94413685c1cdbc9ff0cdfaade62b0 and f4c24a07aa624e787e345b7c9feebecd3ec92c77 , you should be able to run mlcp unit test. Can you run the tests against your branch and let us know the result?

**Comment by hansenmc** [comment]
Regarding the first question, yes, you can run each project independently. 
- if present working directory is marklogic-contentpump/mapreduce/ or marklogic-contentpump/mlcp/, `mvn test` will execute just that module
- if the present working directory is marklogic-contentpump
  - `mvn test` will test both modules.
  - you can specify which module to target `mvn -pl mapreduce test` or `mvn -pl mlcp test`

Although, the mlcp module loads the mapreduce jar with a relative path, so the mapreduce jar has to have been generated first. I was running `mvn -pl mapreduce verify`, then `mvn test`

Each project should behave the same as before. I just moved the common properties, plugins, dependencies up into the parent pom. Using [DependencyManagement](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management) and [PluginManagement](https://maven.apache.org/pom.html#Plugin_Management) and top level properties allows you to inherit those settings to ensure that they are consistently applied in the child modules, and makes maintenance easier. The plugins defined in the parent will only take effect if declared in the sub-module, and you can always enhance/override a definition in the sub-module, but if you want to inherit what is defined in the parent - you just have to reference the artifactId.

Previously, I believe 3 tests were failing. I'm rebasing against the /develop branch and will execute the tests. Should I be using ML 8 or 9-ea2, or should it matter?

**Comment by mattsunsjf** [comment]
I guess what I'm asking is, can we build deliverables separately? So I execute
``` bash
$ mvn clean package -DskipTests=true
```
under root directory of mlcp/mapreduce, does it behavior the same as before?

Maybe I'm missing something here, but when I run above command under marklogic-contentpump directory, I see nothing created under ```deliverables``` directory.

And I also saw this kind of logging warnings during maven build, not sure whether you're aware of:
```
[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /lib
```

**Comment by hansenmc** [comment]
Now I see. It seems that it is invoking the antrun-plugin script to mkdir and copy files **BEFORE** the zip files are created by maven-assembly-plugin. When I organized the plugins, it affected the execution order, and we need antrun-plugin to execute **AFTER** maven-assembly-plugin. For plugins executed in the same phase, [the order listed in the pom will be used to control execution](https://www.mkyong.com/maven/maven-plugin-execution-order-in-same-phase/). I'll move antrun below the assembly plugin, for now.

However, does the antrun plugin need to create the zip in the `package` phase? It could be run in later phases `verify`, `install`, or `deploy`, which would follow the execution of `integration-test` (if/when the tests are split between unit and integration phases). Putting it in one of the later phases would ensure that the deliverable folder is only populated when all tests pass(assuming it is run without -DskipTests for final builds).

As for the warnings, it looks like it is complaining about the `/` used in the `<outputDirectory>/</outputDirectory>` of the  descriptor files used by the make-assembly execution.

**Comment by hansenmc** [comment]
There are a number of tests that are currently failing. It seems that it's fails to load the `lc.xqy` module, which is necessary for most tests. I am executing the `mvn test` on my machine, but my  MarkLogic instance is hosted on a VM (with NAT so that it communicates as localhost). When it attempts to load the modules, it uses an eval() to load from the filesystem with `xdmp:document-load("file://...` which does not exist on my VM running the MarkLogic instance, and thows exceptions about a missing file. 

I need to checkout and run on the VM...

**Comment by hansenmc** [comment]
One test is failing at the moment: `TestCopy.testCopyTemporalDoc()`. It loads the document into the Documents database, but seems to be failing to copy to the `CopyDst` database, so it fails the assertion to count from the `mycollection` collection.

```
Results :

Failed tests: 
  TestCopy.testCopyTemporalDoc:506 expected:<[1]> but was:<[0]>

Tests run: 180, Failures: 1, Errors: 0, Skipped: 0

```

**Comment by mattsunsjf** [comment]
Moving execution of antrun to `verify` phase makes sense to me if we have separated unit tests and integration tests. But for now, let's bind it with `package` phase as before.

Because test resources are located on local file system, you want to have ML instance running on the same machine as MLCP. 

I'm not sure why `TestCopy.testCopyTemporalDoc()` failed, what's the error stack?

**Comment by hansenmc** [comment]
Executing `mvn test` with a local MarkLogic instance worked. All tests passed for me.

```
Results :

Tests run: 180, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MarkLogic Content Pump and Connector for Hadoop .... SUCCESS [  0.005 s]
[INFO] MarkLogic Connector for Hadoop ..................... SUCCESS [ 12.986 s]
[INFO] MarkLogic Content Pump ............................. SUCCESS [14:21 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by mattsunsjf** [comment]
Hi Mads,

- I saw some excluded transitive dependencies in mapreduce and mlcp. Was that because they have a version conflict so you explicitly pick it?
- Why is jackson-databind included in mapreduce dependency? I don't think we need it at compile time.

**Comment by mattsunsjf** [comment]
Hi Mads,

Any specific reason for upgrading JENA libraries?

**Comment by hansenmc** [comment]
1. From what I recall the the netty dependency was problematic. Excluding netty and adding an explicit dependency for the desired (newer) netty was necessary to avoid conflicts. For commons-digester, it looks like you could get away with adding an explicit dependency for commons-digester and then you wouldn't need to exclude it from commons-modeler.
2. I don't recall. If doesn't appear that it is needed. I dropped it and was still able to compile and run the tests.   
  - **I have committed and pushed the change to remove jackson-databind on this branch.**
3. I was updating all of the dependencies to the latest-and-greatest, which usually incorporates new features, bug fixes, security patches, etc. It is generally a good practice to upgrade to the latest versions as they become available. Not only to ensure that you get all of the goodness, but also to allow for incremental adjustments, rather than forcing major changes to the codebase to adjust for major release changes (deprecated methods, changes to namespaces, etc.) that can be more difficult to tackle all at once.
  - Is there a specific reason why **NOT** to upgrade the JENA library? 
  - We usually expect clients to upgrade to the latest versions of our software for the same reasons listed above.

**Comment by mattsunsjf** [comment]
resolved by #53

**Pull request closed without merging**
