### PR TITLE
Release 11.2.0

### PR DESCRIPTION
**Pull request by SameeraPriyathamTadikonda**

### CODE REVIEW

**Review by yunzvanessa — APPROVED** [review]
Looks good. Thanks!

**Comment by SameeraPriyathamTadikonda** [comment]
@yunzvanessa  looks like there are conflicts. Would you be able to resolve those?

**Comment by yunzvanessa** [comment]
@abika5 Could you please take a look when you are back?

**Comment by abika5** [comment]
> @abika5 Could you please take a look when you are back?

I will create my own PR for this and resolve it there.

**Pull request closed without merging**
