### PR TITLE
Bug:57185 - Upgrade log4j to log4j2

### PR DESCRIPTION
**Pull request by yunzvanessa**

### CODE REVIEW

**Review by abika5 — COMMENTED** [review]
Hi Vanessa, 

From what i understand, 
1. You have added new log4j and slfj dependencies and removed unnecessary ones in the pom.xml, bindist-mapr.xml and bindist.xml. 
2. There is one more update on the log4j properties file. It got changed to XML file.
3. Because of the avro-tools removal the TestImportBigdata is changed. 

let me know if I missed something

**Comment by yunzvanessa** [comment]
Yes. You are correct

**Review by abika5 — APPROVED** [review]
Looks good to me.

**Comment by yunzvanessa** [comment]
Thanks, Abika!

**Pull request merged**
