### PR TITLE
Change source and target from Java 7 to Java 8.

### LINKED ISSUE #207: configure maven-compiler-plugin for Java 8
The [SegmentAssignmentPolicy uses Long.remainderUnsigned()](https://github.com/marklogic/marklogic-contentpump/blob/cd859b49ec802dc4311cd1168e55fae960c23aeb/src/main/java/com/marklogic/mapreduce/utilities/SegmentAssignmentPolicy.java#L55)

            return (int) Long.remainderUnsigned(u,size);

That function was [introduced in Java 8](https://docs.oracle.com/javase/8/docs/api/java/lang/Long.html#remainderUnsigned-long-long-)

However, the POM has the [maven-compiler-plugin configured with source and target for Java 7](https://github.com/marklogic/marklogic-contentpump/blob/cd859b49ec802dc4311cd1168e55fae960c23aeb/pom.xml#L114)

    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <compilerArgs>
            <arg>-Xlint</arg>
          </compilerArgs>
          <failOnError>true</failOnError>
          <showDeprecation>true</showDeprecation>
          <debug>${compile.debug.symbols.flag}</debug>
          <fork>true</fork>
          <source>1.7</source>
          <target>1.7</target>
        </configuration>
    </plugin>

The MLCP Documentation says that users need Java 8 or later:
https://docs.marklogic.com/guide/mlcp/install#id_44231 
> Oracle/Sun Java JRE 1.8 or later.

The maven-compiler-plugin should be configured for Java 1.8:
https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html

### PR DESCRIPTION
**Pull request by hansenmc**
Resolves #207

### CODE REVIEW

**Comment by hansenmc** [comment]
@itsshivaverma can you review and pull (or reject) this PR? It has been sitting for almost a year.

**Comment by hansenmc** [comment]
11.0.0 is done :)

**Comment by abika5** [comment]
Creating a task to track this

**Comment by abika5** [comment]
This fix is coming up in 11.1.0.

**Pull request closed without merging**
