### PR TITLE
Tallying the bindist.xml and pom.xml dependencies

### PR DESCRIPTION
**Pull request by abika5**

### CODE REVIEW

**Review by yunzvanessa — CHANGES_REQUESTED** [review]
Will hold onto it until the develop branch is open.

**Review by yunzvanessa — COMMENTED** [review]
Will hold onto it until the develop branch is open.

**Comment by abika5** [comment]
Keeping this PR to be reviewed along with the MAPR refactoring

**Comment by yunzvanessa** [comment]
More work needed

**Pull request closed without merging**
